---
- hosts: localhost
  gather_facts: true
  vars:
    - sno_release: "{{ sno_version }}.{{ sno_minor_version }}"
    - sno_util_hostname: "{{ sno_util_host_prefix }}.{{ sno_domain_name }}"
    - sno_vm_name: "{{ sno_cluster_name }}-vm"
    - sno_infraenv_name: "{{ sno_cluster_name }}-infraenv"
    - sno_local_registry: "{{ sno_util_host_prefix }}.{{ sno_domain_name }}:{{ sno_local_registry_port }}"
    - sno_hostname: "{{ sno_host_prefix }}.{{ sno_cluster_name }}.{{ sno_domain_name }}"
     
  roles:
    - role: validate_parms
      when: vars_validated is not defined
    - role: prepare_sno_install
    - role: create_sno_vm

  post_tasks:
    - name: Success message
      debug:
        msg: "Your SNO install started successfully !"
