---
- hosts: localhost
  gather_facts: true
  vars:
    - sno_release: "{{ sno_version }}.{{ sno_minor_version }}"
    - sno_local_release: "{{ 'ocp/openshift' +  sno_release | replace('.','') }}"
    - sno_util_hostname: "{{ sno_util_host_prefix }}.{{ sno_domain_name }}"
    - sno_vm_name: "{{ sno_cluster_name }}-vm"
    - sno_infraenv_name: "{{ sno_cluster_name }}-infraenv"
    - sno_local_registry: "{{ sno_util_host_prefix }}.{{ sno_domain_name }}:{{ sno_local_registry_port }}"
     
  roles:
    - role: validate_parms
      when: vars_validated is not defined
    - role: gen_mirror_server_certs
      when: sno_install_is_airgapped 
    - role: start_mirror_registry
      when: sno_install_is_airgapped 
    - role: start_assisted_installer
    - role: prepare_sno_install
    - role: create_sno_vm
    - role: start_sno_install

  post_tasks:
    - name: Success message
      debug:
        msg: "Your SNO install started successfully !"
